name: sdk_builds
description: Utilities for accessing builds of the Dart SDK.
version: 0.1.0
author: Kevin Moore <kevmoo@google.com>
homepage: https://github.com/kevmoo/sdk_builds.dart
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  googleapis: '>=0.10.0 <0.12.0'
  http: '^0.11.2'
  path: '^1.3.5'
  pub_semver: '^1.2.1'
  quiver: '^0.21.4'
dev_dependencies:
  test: '^0.12.0'
