name: sdk_builds
description: Utilities for accessing builds of the Dart SDK.
version: 0.3.0
author: Kevin Moore <kevmoo@google.com>
homepage: https://github.com/kevmoo/sdk_builds.dart
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  googleapis: ^2.0.0
  http: ^0.13.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  quiver: ^3.0.0
dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.11.0
