name: sdk_builds
description: Utilities for accessing builds of the Dart SDK.
version: 0.0.1
author: Kevin Moore <kevmoo@google.com>
homepage: https://github.com/kevmoo/sdk_builds.dart
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  googleapis: '^0.10.0'
  http: '^0.11.2'
  path: '^1.3.5'
dev_dependencies:
  test: '^0.12.0'
