name: sdk_builds
description: Utilities for accessing builds of the Dart SDK.
version: 0.1.0-dev
author: Kevin Moore <kevmoo@google.com>
homepage: https://github.com/kevmoo/sdk_builds.dart
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  googleapis: '>=0.10.0 <0.12.0'
  http: '^0.11.2'
  path: '^1.3.5'
  pub_semver: any
  quiver: any
dev_dependencies:
  angular2: ^2.0.0-alpha.26
  browser: ^0.10.0+2
  test: '^0.12.0'
transformers:
#- angular2:
#    entry_points:
#        - web/index.dart
#    reflection_entry_points:
#        - web/index.dart
- $dart2js:
    minify: false
    commandLineOptions:
    - --dump-info
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
dependency_overrides:
  angular2:
    path: /Users/kevmoo/source/github/angular_dart_build/angular2
